default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  host: localhost
  host: localhost
  #  pool: 5
  username: test-guru
  password: <%= ENV['TESTGURU_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: TestGuru_development
  host: localhost
  pool: 5

test:
  <<: *default
  database: TestGuru_test


#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: TestGuru_production
  host: localhost
  pool: 5
  username: test-guru
  password: <%= ENV['TESTGURU_DATABASE_PASSWORD'] %>
